---
resource_types:
- defaults:
    commit: ((.:commit))
    repository_url: https://github.com/RoboJackets/apiary-mobile
    token: (("github.com"/token.token))
  name: github-check
  source:
    aws_access_key_id: ((aws/sts/ecr.access_key))
    aws_region: us-east-1
    aws_secret_access_key: ((aws/sts/ecr.secret_key))
    aws_session_token: ((aws/sts/ecr.security_token))
    repository: robojackets/concourse-github-check-resource
  tags:
  - resources
  type: registry-image
- name: pull-request
  source:
    repository: teliaoss/github-pr-resource
  tags:
  - resources
  type: registry-image
resources:
- check_every: 1h0m0s
  icon: android
  name: android-build-box
  public: true
  source:
    repository: mingc/android-build-box
    tag: 1.24.0
  tags:
  - resources
  type: registry-image
- icon: github
  name: apiary-mobile
  public: true
  source:
    branch: evan/ci # TODO: change back to main
    password: (("github.com"/token.token))
    uri: https://github.com/RoboJackets/apiary-mobile
    username: x-access-token
  tags:
  - resources
  type: git
  webhook_token: ((webhook-token))
- icon: source-pull
  name: pull-request
  public: true
  source:
    access_token: (("github.com"/token.token))
    base_branch: main
    repository: RoboJackets/apiary-mobile
  tags:
  - resources
  type: pull-request

jobs:
  - name: build-main
    public: true
    plan:
      - in_parallel:
          steps:
          - do:
            - get: apiary-mobile
              trigger: true
            - file: apiary-mobile/.git/ref
              format: trim
              load_var: commit
              reveal: true
          - get: android-build-box
            tags:
              - large
            timeout: 5m
      - task: print-gradle-version
        config:
          inputs:
          - name: apiary-mobile
          platform: linux
          params:
            GOOGLE_PLAY_PRIVATE_KEY: ((kv/google-play-private-key))
            IS_CI: true
          run:
            args:
            - -exc
            - |
              cd apiary-mobile
              chmod u+x gradlew
              gem install bundler:2.3.1
              bundle install --quiet
              bundle exec fastlane test
            path: sh
        image: android-build-box
        tags:
          - large

  - name: build-pull-request
    public: true
    plan:
    - in_parallel:
          steps:
          - do:
            - get: pull-request
              params:
                integration_tool: checkout
                list_changed_files: true
                submodules: true
              trigger: true
              version: every
            - in_parallel:
                steps:
                - file: pull-request/.git/resource/head_sha
                  format: trim
                  load_var: commit
                  reveal: true
                - file: pull-request/.git/resource/pr
                  format: trim
                  load_var: pull_request_key
                  reveal: true
          - get: android-build-box
            tags:
              - large
            timeout: 5m
    - task: print-gradle-version
      config:
        inputs:
        - name: pull-request
        params:
          PULL_REQUEST_KEY: ((.:pull_request_key))
        platform: linux
        run:
          args:
          - -exc
          - ./gradlew --version
          path: sh
      image: android-build-box
      tags:
        - large
