---
resource_types:
- defaults:
    commit: ((.:commit))
    repository_url: https://github.com/RoboJackets/apiary-mobile
    token: (("github.com"/token.token))
  name: github-check
  source:
    aws_access_key_id: ((aws/sts/ecr.access_key))
    aws_region: us-east-1
    aws_secret_access_key: ((aws/sts/ecr.secret_key))
    aws_session_token: ((aws/sts/ecr.security_token))
    repository: robojackets/concourse-github-check-resource
  tags:
  - resources
  type: registry-image

- name: pull-request
  source:
    repository: teliaoss/github-pr-resource
  tags:
  - resources
  type: registry-image

- name: github-webhook
  defaults:
    github_token: (("github.com"/token.token))
    resources:
      apiary-mobile:
        events:
        - push
        github_uri: https://github.com/RoboJackets/apiary-mobile
      pull-request:
        events:
        - push
        - pull_request
        github_uri: https://github.com/RoboJackets/apiary-mobile
    webhook_token: ((webhook-token))
  source:
    aws_access_key_id: ((aws/sts/ecr.access_key))
    aws_region: us-east-1
    aws_secret_access_key: ((aws/sts/ecr.secret_key))
    aws_session_token: ((aws/sts/ecr.security_token))
    repository: robojackets/concourse-github-webhook-resource
  tags:
  - resources
  type: registry-image

resources:
- check_every: 1h0m0s
  icon: android
  name: android-build-box
  public: true
  source:
    repository: mingc/android-build-box
    tag: 1.24.0
  tags:
  - resources
  type: registry-image

- icon: github
  name: apiary-mobile
  public: true
  source:
    branch: evan/ci # TODO: change back to main
    password: (("github.com"/token.token))
    uri: https://github.com/RoboJackets/apiary-mobile
    username: x-access-token
  tags:
  - resources
  type: git
  webhook_token: ((webhook-token))

- icon: source-pull
  name: pull-request
  public: true
  source:
    access_token: (("github.com"/token.token))
    base_branch: main
    repository: RoboJackets/apiary-mobile
    disable_forks: true
  tags:
  - resources
  type: pull-request
  webhook_token: ((webhook-token))

- name: tests-check
  type: github-check
  icon: check
  public: true
  source:
    check_name: Apiary Android Tests
    resource_name: tests-check
  tags:
    - resources

- name: pr-build-check
  type: github-check
  icon: check
  public: true
  source:
    check_name: Pull Request Build
    resource_name: pr-build-check
  tags:
    - resources

- icon: webhook
  name: webhooks
  public: true
  source: null
  tags:
  - resources
  type: github-webhook
  

jobs:
  - name: build-main
    public: true
    plan:
      - in_parallel:
          steps:
          - do:
            - get: apiary-mobile
              trigger: true
            - file: apiary-mobile/.git/ref
              format: trim
              load_var: commit
              reveal: true
            - put: tests-check
              inputs: []
          - get: android-build-box
            tags:
              - large
            timeout: 5m
      
      - task: prepare-env
        image: android-build-box
        tags:
          - large
        file: apiary-mobile/ci/pipelines/tasks/prepare-env.yml
        input_mapping:
          source: apiary-mobile
        output_mapping:
          source: apiary-mobile

      - task: run-tests
        image: android-build-box
        tags:
          - large
        file: apiary-mobile/ci/pipelines/tasks/run-tests.yml
        input_mapping:
          source: apiary-mobile
        output_mapping:
          source: apiary-mobile
        on_abort:
          put: tests-check
          inputs:
            - tests-check
          params:
            conclusion: cancelled
        on_error:
          put: tests-check
          inputs:
            - tests-check
          params:
            conclusion: action_required
        on_failure:
          put: tests-check
          inputs:
            - tests-check
          params:
            conclusion: failure
            summary: Review the output within Concourse.
            title: Tests failed
      
      - put: tests-check
        params:
          conclusion: success
          summary: Tests ran successfully
          title: Tests passed
        inputs:
          - tests-check

      - put: webhooks
        inputs: []

  - name: build-pull-request
    public: true
    plan:
    - in_parallel:
          steps:
          - do:
            - get: pull-request
              params:
                integration_tool: checkout
                list_changed_files: true
                submodules: true
              trigger: true
              version: every
            - in_parallel:
                steps:
                - do:
                  - file: pull-request/.git/resource/head_sha
                    format: trim
                    load_var: commit
                    reveal: true
                  - file: pull-request/.git/resource/pr
                    format: trim
                    load_var: pull_request_key
                    reveal: true
                  - put: tests-check
                    inputs: []
                  - put: pr-build-check
                    inputs: []
          - get: android-build-box
            tags:
              - large
            timeout: 5m

    - task: prepare-env
      image: android-build-box
      tags:
        - large
      file: pull-request/ci/pipelines/tasks/prepare-env.yml
      input_mapping:
        source: pull-request
      output_mapping:
        source: pull-request

    - task: run-tests
      image: android-build-box
      tags:
        - large
      file: pull-request/ci/pipelines/tasks/run-tests.yml
      input_mapping:
        source: pull-request
      output_mapping:
        source: pull-request
      on_abort:
        put: tests-check
        inputs:
          - tests-check
        params:
          conclusion: cancelled
      on_error:
        put: tests-check
        inputs:
          - tests-check
        params:
          conclusion: action_required
      on_failure:
        put: tests-check
        inputs:
          - tests-check
        params:
          conclusion: failure
          summary: Review the output within Concourse.
          title: Tests failed
    
    - put: tests-check
      params:
        conclusion: success
        summary: Tests ran successfully
        title: Tests passed
      inputs:
        - tests-check

    - task: upload-pr-build
      file: pull-request/ci/pipelines/tasks/pr-build.yml
      image: android-build-box
      tags:
        - large
      on_abort:
        put: pr-build-check
        inputs:
          - pr-build-check
        params:
          conclusion: cancelled
      on_error:
        put: pr-build-check
        inputs:
          - pr-build-check
        params:
          conclusion: action_required
      on_failure:
        put: pr-build-check
        inputs:
          - pr-build-check
        params:
          conclusion: failure
          summary: Review the output within Concourse.
          title: Pull request build failed

    - put: pr-build-check
      params:
        conclusion: success
        summary: Pull request build created successfully
        title: PR build created
      inputs:
        - pr-build-check

    - put: webhooks
      inputs: []
