# prepare-env task or equivalent should be run before using this
inputs:
- name: source

outputs:
- name: source

platform: linux
run:
    dir: source
    args:
    - -exc
    - |
        bundle exec fastlane detekt
    path: sh
